#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: configuration unique de ce Mac pour l'intégration Capucine
# (LM Studio + vocal), pilotée depuis le Raspberry Pi par SSH.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

PI_PUBLIC_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKlTuT4rmumS0ZP3Q9gS9yfI91q+Gy9QpuBYKu8dpa2S capucine-pi-to-mac"
LMS_BIN="$HOME/.lmstudio/bin/lms"
MAC_MODEL="qwen3-coder-30b-a3b-instruct-mlx"
CAPUCINE_MAC_DIR="$HOME/.capucine-mac"
LAUNCH_AGENT_PATH="$HOME/Library/LaunchAgents/com.capucine.lmstudio-server.plist"
REPO_SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

banner "Capucine — configuration Mac (LM Studio + vocal)"
say "Ce Mac va devenir joignable en SSH par clé (sans mot de passe) depuis le"
say "Raspberry Pi, pour exécuter à distance la génération de texte (LM Studio)"
say "et de vocal (say + ffmpeg). Chaque étape est sûre à rejouer plusieurs fois."

# ── Stage 1 : Remote Login (serveur SSH) ───────────────────────────────────
stage "Activer Remote Login (serveur SSH)"
# systemsetup -getremotelogin sort avec le code 0 même sans droits admin, en
# imprimant un message d'erreur sur stdout ("You need administrator access
# to run this tool...") au lieu d'échouer — on le détecte explicitement,
# plutôt que d'afficher ce message comme s'il s'agissait d'un vrai statut.
current_status="$(systemsetup -getremotelogin 2>/dev/null || echo "inconnu")"
if [[ "$current_status" == *"administrator access"* ]]; then
  current_status="inconnu (nécessite les droits admin pour lire le statut)"
fi
say "Statut actuel : $current_status"
if [[ "$current_status" == *"On"* ]]; then
  note "Remote Login est déjà activé, rien à faire."
else
  warn "Cette commande demande votre mot de passe administrateur (sudo)."
  if confirm "Activer Remote Login maintenant ?"; then
    sudo systemsetup -setremotelogin on
    note "Remote Login activé."
  else
    warn "Étape ignorée — le Pi ne pourra pas se connecter tant que ce n'est pas fait."
    SKIPPED+=("Activer Remote Login : sudo systemsetup -setremotelogin on")
  fi
fi
pause

# ── Stage 2 : clé publique du Pi dans authorized_keys ──────────────────────
stage "Autoriser la clé SSH dédiée du Pi"
say "Le Pi utilise une clé ed25519 dédiée (générée sur le Pi, jamais partagée"
say "en tant que clé privée) pour se connecter à ce Mac."
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"
touch "$HOME/.ssh/authorized_keys"
chmod 600 "$HOME/.ssh/authorized_keys"
if grep -qF "capucine-pi-to-mac" "$HOME/.ssh/authorized_keys" 2>/dev/null; then
  note "La clé du Pi est déjà autorisée, rien à faire."
else
  printf '%s\n' "$PI_PUBLIC_KEY" >> "$HOME/.ssh/authorized_keys"
  note "Clé du Pi ajoutée à ~/.ssh/authorized_keys."
fi
pause

# ── Stage 3 : déploiement des scripts de génération sur le Mac ────────────
stage "Copier les scripts de génération (texte + vocal)"
say "Ces deux scripts sont exécutés par le Pi via SSH pour générer le texte"
say "(LM Studio) et le vocal (say + ffmpeg) du digest."
mkdir -p "$CAPUCINE_MAC_DIR"
cp "$REPO_SCRIPTS_DIR/mac_lmstudio_generate.py" "$CAPUCINE_MAC_DIR/mac_lmstudio_generate.py"
cp "$REPO_SCRIPTS_DIR/mac_say_to_ogg.sh" "$CAPUCINE_MAC_DIR/mac_say_to_ogg.sh"
chmod +x "$CAPUCINE_MAC_DIR/mac_lmstudio_generate.py" "$CAPUCINE_MAC_DIR/mac_say_to_ogg.sh"
note "Scripts copiés dans $CAPUCINE_MAC_DIR."
pause

# ── Stage 4 : LaunchAgent pour démarrer LM Studio automatiquement ─────────
stage "Démarrage automatique du serveur LM Studio"
say "Un LaunchAgent lance 'lms server start' puis charge le modèle $MAC_MODEL"
say "à chaque ouverture de session — sans dépendre de l'interface de LM Studio."
if [[ ! -x "$LMS_BIN" ]]; then
  warn "lms introuvable à $LMS_BIN — vérifiez votre installation LM Studio."
  SKIPPED+=("LaunchAgent LM Studio : lms introuvable à $LMS_BIN")
else
  cat > "$LAUNCH_AGENT_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.capucine.lmstudio-server</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>$LMS_BIN server start; $LMS_BIN ps 2>/dev/null | grep -q "$MAC_MODEL" || $LMS_BIN load "$MAC_MODEL" -y</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/capucine-lmstudio-launchagent.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/capucine-lmstudio-launchagent.log</string>
</dict>
</plist>
PLIST
  launchctl unload "$LAUNCH_AGENT_PATH" >/dev/null 2>&1 || true
  launchctl load "$LAUNCH_AGENT_PATH"
  note "LaunchAgent installé et chargé ($LAUNCH_AGENT_PATH)."
  note "Il se déclenchera automatiquement aux prochaines ouvertures de session."
fi
pause

# ── Stage 5 : vérification finale ──────────────────────────────────────────
stage "Vérification"
say "Statut Remote Login :"
remotelogin_status="$(systemsetup -getremotelogin 2>/dev/null || echo "inconnu")"
if [[ "$remotelogin_status" == *"administrator access"* ]]; then
  warn "impossible de lire le statut sans droits admin (relancez avec sudo pour vérifier)"
else
  note "$remotelogin_status"
fi
say "Statut serveur LM Studio :"
# lms écrit ce message sur stderr, pas stdout — ne pas le supprimer ici.
"$LMS_BIN" server status || warn "lms indisponible"
say "Test de connexion SSH en boucle locale (avec la clé du Pi, si vous l'avez copiée ici) :"
note "Ce test utilise votre propre clé locale, juste pour vérifier que sshd répond :"
if ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new "$(whoami)@localhost" true 2>/dev/null; then
  note "✓ sshd répond correctement en local."
else
  warn "Impossible de confirmer via une connexion locale (pas forcément un problème :"
  warn "vérifiez plutôt depuis le Pi avec sa propre clé une fois ce wizard terminé)."
fi
printf '\n'
say "Valeurs à reporter dans le .env du Pi (/home/fsalazar/04-capucine/.env) :"
note "MAC_HOST=<IP locale de ce Mac, ex. 10.0.0.8>"
note "MAC_SSH_USER=$(whoami)"
note "MAC_SSH_KEY_PATH=/home/fsalazar/.ssh/capucine_mac_ed25519"
note "MAC_ADDRESS=<adresse MAC de l'interface réseau du Mac>"
note "MAC_MODEL=$MAC_MODEL"
pause

finish
